server.port=8080

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5433/main
spring.datasource.username=user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=none

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
stats-server.url=http://localhost:9090