services:
  stats-db:
    image: postgres:16.1
    container_name: stats-postgres
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  main-db:
    image: postgres:16.1
    container_name: main-postgres
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"