server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/events
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: update

  cloud:
    openfeign:
      okhttp:
        enabled: true

stats:
  service-id: stats-server

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      userService:
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50

      requestService:
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50

  retry:
    instances:
      userService:
        maxAttempts: 3
        waitDuration: 500ms

      requestService:
        maxAttempts: 3
        waitDuration: 500ms

grpc:
  client:
    collector:
      address: discovery:///collector
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

    analyzer:
      address: discovery:///analyzer
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext